repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: ^infra/helm/templates/
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.4"
    hooks:
      - id: ruff-check
        args: [ --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      - id: terraform_fmt
      - id: infracost_breakdown
        args:
          - --args=--path=./infra
        verbose: true
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
          - --hook-config=--use-standard-markers=true     # Boolean. Defaults to true (v1.93+), false (<v1.93). Set to true for compatibility with terraform-docs
            # The following two options "--custom-marker-begin" and "--custom-marker-end" are ignored if "--use-standard-markers" is set to false
          - --hook-config=--custom-marker-begin=<!-- BEGIN_TF_DOCS -->  # String.
                                                          # Set to use custom marker which helps you with using other formats like asciidoc.
                                                          # For Asciidoc this could be "--hook-config=--custom-marker-begin=// BEGIN_TF_DOCS"
          - --hook-config=--custom-marker-end=<!-- END_TF_DOCS -->  # String.
                                                          # Set to use custom marker which helps you with using other formats like asciidoc.
                                                          # For Asciidoc this could be "--hook-config=--custom-marker-end=// END_TF_DOCS"
          - --hook-config=--custom-doc-header="# "

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: Dockerfile$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]

  - repo: https://github.com/PyCQA/eradicate
    rev: 3.0.0
    hooks:
      - id: eradicate

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  # - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
  #   rev: v0.0.8
  #   hooks:
  #     - id: k8svalidate
  #       args: [--exclude, "**/*.patch.yaml"]
  #       files: .yaml$
