repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: (^infra/helm/templates/|^mkdocs.yml$)
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.4"
    hooks:
      - id: ruff-check
        args: [ --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
      - id: infracost_breakdown
        args:
          - --args=--path=./infra
        verbose: true
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        files: Dockerfile$

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]

  - repo: https://github.com/PyCQA/eradicate
    rev: 3.0.0
    hooks:
      - id: eradicate

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  # - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
  #   rev: v0.0.8
  #   hooks:
  #     - id: k8svalidate
  #       args: [--exclude, "**/*.patch.yaml"]
  #       files: .yaml$
