services:
  app:
    build:
      context: .
      dockerfile: trash.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /Users/jojobizarre/.config/gcloud/application_default_credentials.json:/app/credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
