apiVersion: apps/v1
kind: Deployment
metadata: #Dictionary
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec: # Dictionary
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata: # Dictionary
      labels: # Dictionary
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers: # List
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # readinessProbe:
          #     httpGet:
          #       scheme: HTTP
          #       path: /app2/index.html
          #       port: 80
          #     initialDelaySeconds: 10
          #     periodSeconds: 15
          #     timeoutSeconds: 5
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
