# Créer un nom de domain avec cloud domain name (Cloud Domain sur l'ui de GCP puis vérifier sur Cloud DNS qu'il est bien disponible)
## Lien : https://github.com/stacksimplify/google-kubernetes-engine/blob/main/37-Google-Cloud-Domains/README.md

# Créer une adresse ip externe reserver et l'associer au domaine créer (VPC > Adresse IP > Réserver une adresse ip externe | Cloud Dns > Ajouter une règle de routage)
## Lien : https://github.com/stacksimplify/google-kubernetes-engine/blob/main/38-GKE-Ingress-ExternalIP/README.md

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}-ingress
  annotations:
    # External Load Balancer
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    # Static IP for Ingress Service
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.annotations.global_static_ip_name | default "template-external-ip" }}
    # Google Managed SSL Certificates
    networking.gke.io/managed-certificates: {{ .Values.ingress.annotations.managed_certificates | default "managed-cert-for-ingress" }}
    # SSL Redirect HTTP to HTTPS
    networking.gke.io/v1beta1.FrontendConfig: {{ .Values.ingress.annotations.frontend_config | default "my-frontend-config" }}
    # External DNS - For creating a Record Set in Google Cloud Cloud DNS
    {{- if .Values.ingress.registerDns }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.annotations.external_dns_hostname | default "templatejojotest.com" }}
    {{- end }}
spec:
  defaultBackend:
    service:
      name: {{ include "helm.fullname" . }}
      port:
        number: {{ .Values.service.port }}
