# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5

image:
  repository: stacksimplify/kube-nginxapp1
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "event-driven-api"

serviceAccount:
  create: true
  automount: true
  annotations:
    iam.gke.io/gcp-service-account: gke-sa@dataascode.iam.gserviceaccount.com
  name: "event-driven-api-sa"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  annotations: {}

ingress:
  enabled: true
  registerDns: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: template-external-ip
    networking.gke.io/managed-certificates: managed-cert-for-ingress
    networking.gke.io/v1beta1.FrontendConfig: my-frontend-config
    external-dns.alpha.kubernetes.io/hostname: templatejojotest.com
  hosts:
    - host: templatejojotest.com
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    memory: 256Mi
    cpu: 300m
  limits:
    memory: 512Mi
    cpu: 600m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# GKE Specific Configurations

backendConfig:
  name: my-backendconfig
  timeoutSec: 42
  drainingTimeoutSec: 62
  logging:
    enable: true
    sampleRate: 1.0
  cdn:
    enabled: true
    includeHost: true
    includeProtocol: true
    includeQueryString: false
  securityPolicy:
    name: cloud-armor-policy

frontendConfig:
  name: my-frontend-config
  redirectToHttps: true
  sslPolicy: production-ssl-policy

persistence:
  enabled: true
  claimName: pv-claim
  accessMode: ReadWriteOnce
  size: 50Gi
  storageClass: standard-rwo
