apiVersion: apps/v1
kind: Deployment
metadata: #Dictionary
  name: app-deployement
spec: # Dictionary
  replicas: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata: # Dictionary
      name: app-pod
      labels: # Dictionary
        app: app  # Key value pairs
    spec:
      containers: # List
        - name: app-container
          image: stacksimplify/kube-nginxapp1:1.0.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 128Mi # 128 MebiByte is equal to 135 Megabyte (MB)
              cpu: 200m # `m` means milliCPU
            limits:
              memory: 256Mi
              cpu: 400m  # 1000m is equal to 1 VCPU core
          # readinessProbe:
          #     httpGet:
          #       scheme: HTTP
          #       path: /app2/index.html
          #       port: 80
          #     initialDelaySeconds: 10
          #     periodSeconds: 15
          #     timeoutSeconds: 5
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: pv-claim
