name: Cleanup Ephemeral Environment
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
       - "api/**"
       - "infra/helm/**"

env:
  CONFIG_FILE: config.yaml
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load config from config.yaml
        id: config
        run: |
          echo "GCP_PROJECT_ID=$(yq '.gcp.project_id' ${{ env.CONFIG_FILE }})" >> $GITHUB_ENV
          echo "GCP_ZONE=$(yq '.gcp.region' ${{ env.CONFIG_FILE }})" >> $GITHUB_ENV
          echo "GKE_CLUSTER_NAME=$(yq '.gke.cluster_name' ${{ env.CONFIG_FILE }})" >> $GITHUB_ENV

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        run: |
            gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --zone ${{ env.GCP_ZONE }} --project ${{ env.GCP_PROJECT_ID }}

      - name: Calculate Namespace
        id: ns
        run: |
          REF_NAME="${{ github.event.pull_request.head.ref }}"
          SANITIZED_NAME=$(echo "$REF_NAME" | tr '[:upper:]' '[:lower:]' | tr '/' '-' | sed 's/[^a-z0-9-]//g')
          echo "namespace=$SANITIZED_NAME" >> $GITHUB_OUTPUT

      - name: Delete Ephemeral Eventarc Trigger
        run: |
          NAMESPACE="${{ steps.ns.outputs.namespace }}"
          TRIGGER_NAME="trigger-ingest-${NAMESPACE}"
          
          echo "Deleting Ephemeral Trigger: $TRIGGER_NAME"
          
          # Delete trigger if exists, ignore error if not found
          gcloud eventarc triggers delete $TRIGGER_NAME \
            --location=${{ env.GCP_ZONE }} \
            --quiet || echo "Trigger $TRIGGER_NAME not found or already deleted"

      - name: Delete Environment
        run: |
          NAMESPACE="${{ steps.ns.outputs.namespace }}"
          
          echo "Cleaning up namespace: $NAMESPACE"

          # Uninstall Helm release
          helm uninstall event-driven-api --namespace $NAMESPACE || true

          # Delete Namespace
          kubectl delete namespace $NAMESPACE --ignore-not-found=true
