name: Cleanup Environment
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
       - "api/**"
       - "infra/helm/**"

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER_NAME: template-gke-cluster
      GCP_ZONE: europe-west1
      GCP_PROJECT_ID: dataascode
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        run: |
            gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --zone ${{ env.GCP_ZONE }} --project ${{ env.GCP_PROJECT_ID }}

      - name: Delete Environment
        run: |
          REF_NAME="${{ github.event.pull_request.head.ref }}"
          # Sanitize branch name to match namespace creation logic
          SANITIZED_NAME=$(echo "$REF_NAME" | tr '[:upper:]' '[:lower:]' | tr '/' '-' | sed 's/[^a-z0-9-]//g')

          echo "Cleaning up namespace: $SANITIZED_NAME"

          # Uninstall Helm release
          helm uninstall event-driven-api --namespace $SANITIZED_NAME || true

          # Delete Namespace
          kubectl delete namespace $SANITIZED_NAME --ignore-not-found=true
